# Generated by Django 5.2.1 on 2025-05-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Categoty',
            new_name='category',
        ),
    ]
