# Generated by Django 5.2.1 on 2025-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categoty_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
