# Generated by Django 5.2.1 on 2025-05-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_salesitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='price',
        ),
    ]
